apiVersion: v1
kind: Secret
metadata:
  name: educaonline-secrets
  namespace: educaonline
  labels:
    app.kubernetes.io/name: educaonline-secrets
    app.kubernetes.io/part-of: educaonline-platform
type: Opaque
stringData:
  # SQLite Connection Strings
  SQLITE_CONNECTION: "Data Source=app.db"
  # RabbitMQ
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  RABBITMQ_CONNECTION: "host=rabbitmq-service:5672;username=guest;password=guest;publisherConfirms=true;timeout=30"
  # JWT
  JWT_SEGREDO: "EDUCAONLINE_SECRET_KEY_SUPER_SEGURA_2024_DEVXPERT_K8S"
